config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root 'page#index'
  
  resources :teams, only: [:create]
  resources :page, only: [:index]
  resources :timer
  
  namespace :admin do
    resources :home
    resources :contests
    resources :shirts do
      get 'give' => 'shirts#give'
      get 'ungive' => 'shirts#ungive'
    end
    
    get 'teams/all' => 'teams#all'
    resources :teams do
      post 'verify' => 'teams#verify'
      resources :players
    end
  end
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contest.rb
class Contest < ActiveRecord::Base
  
end

app/models/player.rb
class Player < ActiveRecord::Base
  validates_uniqueness_of :email, message: "is already registered: %{value}"  
  validates_presence_of :email, :name, :team
  belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
  validates_uniqueness_of :name, message: "Sorry, but that team name is already taken"
  
  has_many :players, dependent: :destroy
  
  scope :verified, -> { where(Team.arel_table[:verified].eq(true)) }
end

app/controllers/admin/contests_controller.rb
class Admin::ContestsController < ApplicationController
  before_action :authenticate_admin!

  layout :choose_layout
  
  def index
    @contests = Contest.all
  end
  
  def show
    @contest = Contest.find(params[:id])
  end
  
  def new
    if(params[:start_late])
      contest = Contest.create
      contest.created_at = DateTime.now
      contest.save
    else
      contest = Contest.create
      contest.created_at = DateTime.new(2016, 8, 26, 18, 0, 0, "+12").in_time_zone("UTC")
      contest.save
    end
    redirect_to admin_contests_path
  end
  
  def destroy
    contest = Contest.find(params[:id])
    contest.destroy!
    
    redirect_to admin_contests_path
  end

  private

  def choose_layout
    case action_name
    when "show"
      "time"
    else
      "admin"
    end
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_action :authenticate_admin!

	layout "admin" 
  
	def index
	end
end

app/controllers/admin/shirts_controller.rb
class Admin::ShirtsController < ApplicationController
  before_action :authenticate_admin!

  layout "admin" 

  def index
    @players = Player.all.order(:created_at)
  end

  def give
    player = Player.find(params[:shirt_id])
    player.got_shirt = true
    player.save!
    redirect_to action: :index
  end

  def ungive
    player = Player.find(params[:shirt_id])
    player.got_shirt = false
    player.save!
    redirect_to action: :index
  end
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < ApplicationController
  before_action :authenticate_admin!
  
  layout "admin" 
  
  def index
    @teams = Team.all
  end
  
  def show
    @team = Team.find(params[:id])
  end
  
  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    
    redirect_to admin_teams_url
  end
  
  def all
    @players = Player.all
  end
  
  def verify
    @team = Team.find(params[:team_id])
    @team.verified = true
    @team.save
    
    redirect_to admin_teams_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  	@teams = Team.verified
    @contest_running = Contest.any?
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    begin
      ActiveRecord::Base.transaction do
        team = Team.create!(name: params[:team_name])
        
        params[:players].each do |player|
          team.players.create!({
            email: player[:email],
            name: player[:player_name],
            shirt_size: player[:shirt_size]
          })
        end
      end
    rescue ActiveRecord::RecordInvalid => e
      render json: { success: false, message: e.message } and return
    end
    
    render json: { success: true } and return
  end
end

app/controllers/timer_controller.rb
class TimerController < ApplicationController
  def index
    @contest = Contest.all.last
    if @contest
      render "admin/contests/show" and return
    end
  end
end

app/helpers/admin/contest_helper.rb
module Admin::ContestHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/shirts_helper.rb
module Admin::ShirtsHelper
end

app/helpers/admin/teams_helper.rb
module Admin::TeamsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active?(check)
    	return 'active' if current_page?(check)
    	''
  	end
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/timer_helper.rb
module TimerHelper
end

app/views/admin/contests/index.html.erb
<h2>Contests</h2>

<div id="start-buttons">
  <%= link_to "Start", new_admin_contest_path %>
  <%= link_to "Start Late", new_admin_contest_path(:start_late => true) %>
</div>

<table>
  <tr>
    <th>Started at</th>
    <th>Actions</th>
  </tr>
  
  <% @contests.each do |c| %>
    <tr>
      <td><%= c.created_at %></td>
      <td>
        <%= link_to "Show timer", admin_contest_path(c) %>
        <%= link_to "Delete", admin_contest_path(c), method: :delete %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/contests/show.html.erb
<header id="home">
  <div id="stars" class="art-container"></div>
   <div id='clouds' class='art-container'></div>
   <div id='fly' class='art-container'>
      <div id='kite'></div>
      <div id='line'></div>
      <div id='flyer'></div>
    </div>
  <div class="container table">
    <div id="splash-container" class="vert-align">
      <div id="splash" class="row">
        <div id="splash-text" class="twelve columns">
			<div class="timer" data-created-at="<%= @contest.created_at.to_i %>">
			  <div id="started-at"><%= @contest.created_at %></div>
			  <h1 id="countdown"></h1>
			</div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/admin/home/index.html.erb
<p>~</p>

app/views/admin/shirts/index.html.erb
<table>
  <tr>
    <th>Player name</th>
    <th>Team</th>
    <th>Shirt size</th>
    <th>Sign up date</th>
    <th>Got shirt</th>
    <th></th>
  </tr>


  <% @players.each do |player| %>
    <tr>
      <td><%= player.name %></td>
      <td><%= player.team.name %></td>
      <td><%= player.shirt_size %></td>
      <td><%= player.created_at %></td>
      <td><%= player.got_shirt ? "Yes" : "No" %></td>
      <td><%= player.got_shirt ? link_to("Ungive shirt", admin_shirt_ungive_path(player)) : link_to("Give shirt", admin_shirt_give_path(player)) %></td>
    </tr>
  <% end %>
</table>

app/views/admin/teams/all.html.erb
<h2>All Entrants</h2>
<p><%= link_to "< Back", admin_teams_url %></p>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Team</th>
    <th>Shirt size</th>
  </tr>

  <% @players.sort { |a, b| a.team.name <=> b.team.name }.each do |player| %>
    <tr>
      <td><%= player.name %></td>
      <td><%= player.email %></td>
      <td><%= player.team.try! :name %></td>
      <td><%= player.shirt_size %></td>
    </tr>
  <% end %>
</table>

app/views/admin/teams/index.html.erb
<h2>Teams</h2>
<p>
  Omg! <%= @teams.count %> teams and <%= Player.all.count %> players already! 
  <%= link_to "Show all players", admin_teams_all_path %>
</p>

<table>
  <tr>
    <th>Team name</th>
    <th>Number of players</th>
    <th colspan>Actions</th>
  <tr />
  
  <% @teams.each do |team| %>
    <tr>
      <td><%= link_to team.name, admin_team_url(team) %></td>
      <td><%= team.players.count %></td>
      <td>
        <%= link_to "Delete", admin_team_url(team), method: :delete %>
        
        <% if !team.verified %>
         | <%= link_to "Verify", admin_team_verify_url(team), method: :post %>
        <% else %>
         | (verified)
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/teams/show.html.erb
<h2>
  Team: <%= @team.name %>
</h2>

<p><%= link_to "< Back", admin_teams_url %></p>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Shirt Size</th>
  </tr>
  
  <% @team.players.each do |player| %>
    <tr>
      <td><%= player.name %></td>
      <td><%= player.email %></td>
      <td><%= player.shirt_size %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#001428">
    <meta name="msapplication-navbutton-color" content="#001428">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <title>Pxljam</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900,900italic,400italic,700italic" rel="stylesheet"> 
    
  </head>
  <body>
    <div class="container">
        <h1>Cheats</h1>
        <nav id="admin-nav">
        <ul>
            <li>
                <%= link_to "Home", admin_home_index_url, :class => active?(admin_home_index_url) %>
            </li>
            <li>
                <%= link_to "Teams", admin_teams_url, :class => active?(admin_teams_url) %>
            </li>
            <li>
                <%= link_to "Contests", admin_contests_url, :class => active?(admin_contests_url) %>
            </li>
            <li>
                <%= link_to "Shirts", admin_shirts_url, :class => active?(admin_shirts_url) %>
            </li>
        </ul>
        </nav>
        <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#001428">
    <meta name="msapplication-navbutton-color" content="#001428">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <title>Pxljam</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="description" content="PxlJam is a 48-hour game making competition. You have exactly 48 hours from the start of the competition to plan, build and submit your game for judging.>
    
    <meta property="og:title" content="Pxljam" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://pxljam.nz" />
    <meta property="og:description" content="PxlJam is a 48-hour game making competition. You have exactly 48 hours from the start of the competition to plan, build and submit your game for judging." />
    <%= tag :meta, property: 'og:image', content: image_url('og.png') %>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900,900italic,400italic,700italic" rel="stylesheet"> 
    
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/time.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#001428">
    <meta name="msapplication-navbutton-color" content="#001428">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <title>Pxljam</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900,900italic,400italic,700italic" rel="stylesheet"> 
    
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/page/_about.html.erb
<h1 class="e">The game jam with the best pixels.</h1>
<p class="feature">
	PxlJam is a 48-hour game making competition. You have exactly 48 hours from the start of the competition to plan, build and submit your game for judging.
</p>
<p>
	PxlJam starts at 6pm on Friday with the announcement of the theme and runs until 6pm Sunday followed by voting and prize giving. Everyone from first-year university students to seasoned game makers, including non-students, are welcome to sign up and make some games.
</p>
<p>
	You will compete in small teams to create a game inspired by a theme. This theme will only revealed at the start of the competition. You must have your game ready by the end of the 48 hours in order to qualify for prizes. There are no restrictions on the amount of preparation your team can do before the event but we discourage you from making game assets beforehand or adapting a pre-made game to the theme. We want you to turn up with an open mind for all possible games that could be made from the theme.
</p>
<p>
	The judging criteria are based on aspects of gameplay, polish, innovation and creativity. These aspects were chosen to reflect the work you do during the competition and rewards teams who focus on the gaming experience more than teams who focus on complexity.
</p>

app/views/page/_contact.html.erb
<p class="feature">You know what to do here.</p>
<form id="contact-form" action="https://formspree.io/xkbljdnm" method="POST">
	<input name="Name" type="text" placeholder="Name" required>
	<input name="Email" type="email" placeholder="Email" required>
	<input name="_subject" type="text" placeholder="Subject" required>
	<textarea name="Message" placeholder="Message" required></textarea>
	<input type="text" name="_gotcha" style="display: none">
	<input id="email-submit" type="submit" value="Send" >
</form>

app/views/page/_enter.html.erb
<h1>Enter</h1>
<p>This year we are managing registrations through Google Forms.</p>
<p>Entry is $30 per person, paid in cash on attendance. Sign-ups are done individually and teams will be formed on the day.</p>
<p>T-shirts come in <a href="https://www.brazenclothing.co.nz/collections/t-shirts/products/as-colour-5001m-staple-mens-marle-tee" target="_blank">Men's</a> and <a href="https://www.brazenclothing.co.nz/collections/t-shirts/products/as-4001-maple-womens-tee" target="_blank">Women's</a> sizes and will be provided on the day to those who sign up at least a week before the event. Those who sign-up later will have to wait for their shirts to be printed in the following week.</p> 
<%= button_to "Enter Now", "https://forms.gle/ax5NStYdjeu39fLL8", style: "float: left;", method: :get, target: "_blank" %>

app/views/page/_faq.html.erb
<div class="six columns">
  <p>
    I didn't sign up, can I still come?
  </p>
  <p>
    We can not guarantee participation for anyone who has not signed up before the competition begins or if we have already reached maximum capacity. In addition, we can not guarantee that a t-shirt would have been printed for you beforehand, but you can still receive one after the event. If you are having difficulty registering while sign ups are open please contact us and we will try to help you out.
  </p>
  <p>
    How/when do I pay?
  </p>
  <p>
    Cash (correct change appreciated) at the start of the event. We don't do pre-payment because it is easier to have people who turn up pay than deal with refunds for those who don't. We do not accept EFTPOS. A team must have all of their members pay in order to be fully registered for submission/prizes but members may drop from the team if they don't turn up.
  </p>
  
  <p>
    What does my entry fee cover?
  </p>
  <p>
    The entry fee gets you a t-shirt, allows you to have your game judeged, and allows you to vote and get prizes. PxlJam is an event run by a non-profit organization and proceeds go towards running the event or future similar events in the interest of the participants.
  </p>
  <p>
    How many people can I have in my team?
  </p>
  <p>
    There is no maximum, but we recommend that inexperienced teams have a maximum of five members, as larger teams are harder to coordinate. If you have more than five members we suggest you split up into two or more smaller groups.
  </p>
  <p>
    Can I have team members who aren't VUW students?
  </p>
  <p>
    Yes. You can even have a team entirely comprised of non-students. We encourage anyone who wants to make a game and compete to join up.
  </p>
  <p>
    I need/don't have a team, can I sign up?
  </p>
  <p>
    Yes. Simply register and during the event you can create a team name if you intend to enter alone, or you can create or join a team with others looking for a team or another member.
  </p>
  <p>
    How much preparation can I do?
  </p>
  <p>
    As long as you are not building a game or creating assets before the competition you can do as much preparation as you want. Creating a game engine or developing code snippets are fair game.
  </p>
  <p>
    I don't have anything prepared, can I still win?
  </p>
  <p>
    Yes. See "How does voting/judging work?". The judging criteria have been selected to ensure that games developed by first time competitors stand a chance against veteran teams. There are plenty of free tools for developing games including <a href="https://www.unrealengine.com/" target="_blank">Unreal Engine</a>, <a href="https://unity3d.com/" target="_blank">Unity</a> and <a href="http://www.yoyogames.com/gamemaker" target="_blank">GameMaker</a>. Some practice with your engine of choice beforehand is recommended.
  </p>
  <p>
    How does voting/judging work?
  </p>
  <p>
    Voting is performed by a combination of voting by your peers and guest judges. The judging criteria are based on aspects of gameplay, polish, innovation, and creativity.
  </p>
</div>
<div class="six columns">
  <p>
    Do you supply food or water?
  </p>
  <p>
    Possibly. We may supply some small provisions such as drinks and snacks during the competition but do not count on it sustaining you. Food runs (especially for pizza) are likely so it doesn't hurt to bring some extra cash. Water is freely available at drinking fountains nearby.
  </p>
  <p>
    What do I need to bring?
  </p>
  <p>
    The only things you are "required" to bring are your entry fee and a computer. Everything else, including food, spare clothes and deodorant, is optional but highly recommended. Please bring headphones if you need sound as there will be a lot of other people who do not want or need to listen to your bad music or repetitive gameplay testing (Looking at you TAFT).
  </p>
  <p>
    Do you have a spare computer for me to use?
  </p>
  <p>
    No. See "What do I need to bring?".
  </p>
  <p>
    Will there be internet?
  </p>
  <p>
    Yes. There is guaranteed internet over VUW's guest WiFi. We will also setup faster wired internet and WiFi, provided we don't run into technical troubles (again).
  </p>
  <p>
    Is there (overnight) parking available?
  </p>
  <p>
    Yes. There is free parking available all weekend, see <a href="#where" data-scroll>below</a> for where to park. Officially it is available from 5pm Friday until 5am Monday, but if you're lucky you could park there earlier on Friday night. We take no responsibility if you get ticketed/clamped before 7pm on the Friday though.
  </p>
  <p>
    Can I go home… please?
  </p>
  <p>
    Yes. You can leave and come back anytime, as many times as you want. In the spirit of game jams, we encourage everyone to spend their time programming at the event. We also want people to look after themselves, which can include sleeping in their own bed instead of on the floor. After-hours you will need a current student ID card to access the building, but you can contact one of the event organizers if you get locked out at any point.
  </p>
  <p>
    Can you take care of my stuff?
  </p>
  <p>
    No. We are not responsible for property damaged or stolen at the event. That said, there are security cameras everywhere and we will provide assistance locating missing items if needed.
  </p>
  <p>
    Can I sleep on site?
  </p>
  <p>
    Yes, but please do it within the rooms we have booked for the event. In general, security do not like people sleeping on campus, current students or not.
  </p>
  <p>
    Is this BluJam?
  </p>
  <p>
    No. This is not <a href="http://blujm.nz/" target="_blank">BluJam</a>.
  </p>
  <p>
    What are the prizes?
  </p>
  <p>
    The prizes are not decided before the competition as they are assembled during and revealed at the end.
  </p>
  <p>
    Do bigger teams mean fewer prizes?
  </p>
  <p>
    No. Prizes are awarded per person on the team, which means whether you are competeing solo or in a team of five you will get the same quality of prizes (if you win one).
  </p>
  <p>
    Why the name PxlJam?
  </p>
  <p>
    No-one knows... but seriously, if you figure it out who originally named it and why, we'd like to know as well.
  </p>
</div>

app/views/page/_old_enter.erb
<% if @contest_running %>
<h1>Hold fire!</h1>
<p>
  Sign-ups are closed at the moment, check back again closer to the next competition.
</p>
<% else %>
<h1 class="a">Enter a team</h1>
<p>Signups are open. $30 per team member.</p>
<p>
  Due to the huge number of recent signups, we may not be able to provide shirts <b>on the competition day</b> for those who sign up after the <b>21st of August</b>. We know how much Pxljam contestants love their t-shirts, so don't worry! We'll order extras as signups roll in and you can pick them up when they've been printed.
</p>
<p>
  Please ensure you provide a correct email address for each member as we may send you resources needed for voting during the competition.
</p>
<%= form_tag teams_url, id: "entry-form", method: :post do |f| %>
<%= text_field_tag :name, nil, placeholder: "Team name", id: "team-name", required: true %>
<div id="name-error" class="error">That team name is taken sorry!</div>
<div id="players">
  <div id="players-title"><div>Players</div></div>
  <div id="player-select">
    <input type="radio" name="player-select" id="player-1" value="1">
    <input type="radio" name="player-select" id="player-2" value="2">
    <input type="radio" name="player-select" id="player-3" value="3">
    <input type="radio" name="player-select" id="player-4" value="4">
    <input type="radio" name="player-select" id="player-5" value="5">
    <label for="player-1" id="1"><div>1</div></label>
    <label for="player-2" id="2"><div>2</div></label>
    <label for="player-3" id="3"><div>3</div></label>
    <label for="player-4" id="4"><div>4</div></label>
    <label for="player-5" id="5"><div>5</div></label>
  </div>
</div>

<div id="team-message"></div>

<div id="player-fields">
  <div id="player-email-default" class="" style="display: none;">
    <div id="error" class="error">This email is already registered to another team</div>
    <input type="text" name="name"/>
    <input type="email" name="email" placeholder="Email"/>
    <div class="shirt-size-select">
      <div class="shirt-size-title"><div>Shirt Size</div></div>
      <!-- <input type="radio" name="shirt-size" id="size-XS" value="XS"> -->
      <!-- <label for="size-XS" id="size-XS"><div>XS</div></label> -->
      <input type="radio" name="shirt-size" id="size-S" value="S">
      <label for="size-S" id="size-S"><div>S</div></label>
      <input type="radio" name="shirt-size" id="size-M" value="M">
      <label for="size-M" id="size-M"><div>M</div></label>
      <input type="radio" name="shirt-size" id="size-L" value="L">
      <label for="size-L" id="size-L"><div>L</div></label>
      <input type="radio" name="shirt-size" id="size-XL" value="XL">
      <label for="size-XL" id="size-XL"><div>XL</div></label>
    </div>
  </div>
</div>
<div id="entry-errors"></div>

<%= submit_tag "Enter", id: "team-submit", disabled: true %>
<% end %>
<% end %>

app/views/page/_where.html.erb
<p>
	Parking is available (officially) from 5pm Friday until 7am Monday in the staff carpark. We recommend parking just south of the Alan MacDiarmid building as it is the easiest way to access the event if you are driving in.
</p>

app/views/page/index.html.erb
<header id="home">
  <div id="stars" class="art-container"></div>
   <div id='clouds' class='art-container'></div>
   <div id='fly' class='art-container'>
      <div id='kite'></div>
      <div id='line'></div>
      <div id='flyer'></div>
    </div>
  <div class="container table">
    <div id="splash-container" class="vert-align">
      <div id="splash" class="row">
        <div id="splash-text" class="twelve columns">
          <!-- <div id="splash-title">Pxljam</div> -->
          <div id="splash-info">
            <div id="logo"></div>
            <p>Victoria University of Wellington</p>
            <p>Room AM101 and AM106</p>
            <p>6pm Friday 13<sup>th</sup> - Sunday 15<sup>th</sup> September 2019</p>
            <a data-scroll class="button" href ="#enter">Enter Team</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- <div id="signup-status">Signups now open!</div> -->
</header>
<nav>
  <ul data-gumshoe>
    <li><a data-scroll href="#home" class="active">Home</a></li>
    <li><a data-scroll href="#about">About</a></li>
    <li><a data-scroll href="#enter">Enter</a></li>
    <li><a data-scroll href="#faq">FAQ</a></li>
    <li><a data-scroll href="#where">Where</a></li>
    <li><a data-scroll href="#contact">Contact</a></li>
  </ul>
</nav>
<div id="sections">
  <section id="about">
    <div class="container">
      <%= render 'about' %>
    </div>
  </section>
  <section id="enter">
    <div class="container">
      <%= render 'enter' %>
      <%= render 'teams' %>
    </div>
  </section>
  <section id="faq">
    <div class="container">
      <h1 class="b">FAQ</h1>
      <div id="questions" class="row">
        <%= render 'faq' %>
      </div>
    </div>
  </section>
  <section id="where">
    <div class="container">
      <h1 class="c">Where is it?</h1>
      <p class="feature">
        PxlJam is hosted at the Kelburn campus of Victoria University of Wellington.
      </p>
      <div class="row">
        <div class="seven columns">
          <a id="map" href="/assets/map.png" target="_blank" title="View full image"></a>
        </div>
        <div class="five columns">
          <%= render 'where' %>
        </div>
      </div>
    </div>
  </section>
  <section id="contact">
    <div class="container">
      <h1 class="d">Got questions?</h1>
      <%= render 'contact' %>
    </div>
  </section>
  <section id="sponsors">
    <div class="container">
      <div class="sponsor large vec"></div>
      <a href="http://acidic.co.nz" target="_blank" class="sponsor acidic" data-tooltip="Site by Acidic"></a>
    </div>
  </section>
</div>

app/views/timer/index.html.erb
No contest currently running :(